#pragma once
#include "Utility.h"
#include "AST.h"
#include "CompilerError.h"


namespace BFC
{
	struct CompilationParams
	{
		/// Specify what to do with the intermediate files
		enum InterOp
		{
			NONE, /// Delete all intermediates
			OBJ,  /// Preserve the object file generated by every bf file
			ALL   /// For debug purposes, saves a text representation of the code, generated at every phase in the compilation process
		};
		/// [NOT SUPPORTED YET] Specify to which compilation phase stop the execution
		enum TargetPhase { TOKEN, PARSE, ANAL, OPT, INTER, FULL };

		bool optimize = true;
		bool verbose = false;
		/// Specify what to do with the intermediate files
		InterOp intermediates = NONE;
		/// Specify the path where to save the intermediates (must be a directory).
		/// If empty: saves the intermediates in the same directory as the file being compiled
		fs::path intermediatesPath;
		/// [NOT SUPPORTED YET] Specify to which compilation phase stop the execution
		TargetPhase tgtPhase = FULL;
		/// Specify the path where to save the output executable (if already exists it must be a file)
		fs::path outputPath;
		/// List of paths to compile.
		/// If a directory is provided, all bf files inside it (recusively) will be compiled
		std::vector<fs::path> tgts;
		/// Path of the main file (execution starts at its beginning and terminates when reaching its EOF).
		/// It must be a file and listed in tgts (or inside a directory provided as a compilation target)
		fs::path main;
		/// Stream where to put the compilation progress messages
		std::ostream* outputStream = &std::cout;


		inline fs::path GetIntermediatePath(const fs::path& file) const {
			return (intermediatesPath.empty() ? file.parent_path() : intermediatesPath);
		}
		inline bool IsMainFile(const fs::path& file) const {
			if (tgts.empty()) return false;
			if (main.empty()) return file == tgts[0];
			else			  return main == file;
		}

		/// Check for errors in the compilation parameters, set default values for empty parameters and recursively find bf files inside directories listed under tgts
		CompilerError Validate();
	};
}